routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\LoginController;
use App\Http\Controllers\SandboxController;
use App\Http\Controllers\AjaxController;
use App\Http\Controllers\AdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [LoginController::class, 'index'])
	->name('welcome');

Route::prefix('sandbox')->group(function () {
	Route::get('/', [SandboxController::class, 'index'])->name('sandbox');
	Route::get('/permissions', [SandboxController::class, 'permissions'])->name('sandbox.permissions');
	Route::get('/permissions/give-me-admin', [SandboxController::class, 'giveMeAdmin'])->name('sandbox.permissions.give-me-admin');
	Route::get('/seed-a-call', [SandboxController::class, 'seedACall'])->name('sandbox.seed.call');
	Route::get('/seed-a-call/randomized', [SandboxController::class, 'seedACallWithRandomness'])->name('sandbox.seed.call.randomized');
});

Route::prefix('admin')->as('admin.')->group(function () {
	Route::get('/', [AdminController::class, 'index'])->name('index');
	Route::get('/topics', [AdminController::class, 'topics'])->name('topics');
	Route::get('/posts', [AdminController::class, 'posts'])->name('posts');
	Route::get('/calls', [AdminController::class, 'calls'])->name('calls');
	Route::get('/users', [AdminController::class, 'users'])->name('users');

	Route::prefix('posts')->as('posts.')->group(function () {
		Route::get('/create', [AdminController::class, 'createPost'])->name('create');
		Route::get('/{post}', [AdminController::class, 'showPost'])->name('show');
		Route::get('/{post}/edit', [AdminController::class, 'editPost'])->name('edit');
	});

	Route::prefix('topics')->as('topics.')->group(function () {
		Route::get('/create', [AdminController::class, 'createTopic'])->name('create');
		Route::get('/{topic}', [AdminController::class, 'showTopic'])->name('show');
		Route::get('/{topic}/edit', [AdminController::class, 'editTopic'])->name('edit');
	});

	Route::prefix('users')->as('users.')->group(function () {
		Route::get('/{user}', [AdminController::class, 'showUser'])->name('show');
		Route::get('/{user}/edit', [AdminController::class, 'editUser'])->name('edit');
	});
});

Route::middleware('auth', 'verified')->group(function () {
	Route::get('dashboard', [SandboxController::class, 'dashboard'])->name('dashboard');
	Route::get('learn', [SandboxController::class, 'learn'])->name('learn');
	Route::get('capture', [SandboxController::class, 'capture'])->name('capture');
	Route::post('capture', [SandboxController::class, 'storeCapture'])->name('capture.store');
	Route::get('profile', [SandboxController::class, 'profile'])->name('profile');

	Route::prefix('ajax')->group(function () {
		Route::get('user', [AjaxController::class, 'user'])->name('ajax.user');
		Route::get('charts', [AjaxController::class, 'chartsData'])->name('ajax.charts');
	});
});


/*Route::get('auth/{provider}', [LoginController::class, 'redirectToProvidedProvider']);
Route::get('auth/{provider}/callback', [LoginController::class, 'handleProvidedProviderCallback']);*/
Route::get('auth/{provider}/webhook', [LoginController::class, 'handleProvidedProviderWebhook']);
Route::get('auth/{provider}/webhook', [LoginController::class, 'handleProvidedProviderWebhook']);


//Route::get('/user', [UserController::class, 'index']);
/*Route::prefix('auth')->group(function () {
	Route::prefix('zoom')->group(function () {
		Route::get('', [ZoomController::class, 'authorize'])->name('authorize');
		Route::get('callback', [ZoomController::class, 'callback'])->name('callback');
		Route::get('webhooks', [ZoomController::class, 'webhooks'])->name('webhooks');
	});
});*/

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use HasFactory, SoftDeletes;

    public $timestamps = true;

    protected $fillable = [
    	'user_id',
    	'topic_id',
    	'title',
    	'content',
    	'avatar',
    	'header',
    	'status',
    	'metadata',
    ];

    protected $casts = [
    	'metadata' => 'array',
        'avatar'    => 'array',
        'header'    => 'array',
    ];

    public function getAvatarUrlAttribute()
    {
        if ($this->avatar != null && false) :
            return asset($this->avatar);
        else :
            return 'https://ui-avatars.com/api/?name=' . str_replace(' ', '+', $this->title) . '&background=fff&color=6777ef&size=100';
        endif;
    }

    public function getHeaderUrlAttribute()
    {
        if ($this->header != null && false) :
            return asset($this->header);
        else :
            return 'https://ui-avatars.com/api/?name=' . str_replace(' ', '+', $this->title) . '&background=fff&color=6777ef&size=500';
        endif;
    }

    public function topic() {
        return $this->belongsTo(Topic::class);
    }
}

resources/views/capture.blade.php
@extends('layouts.backend')

@section('title', 'Capture')

@section('content')
<x-section-header heading="Capture" breadcrumb="capture" />
<div class="row">
  <div class="col-12 mb-4">
      <div class="hero text-white hero-bg-image" style="background-image: url('{{ asset('stisla/img/unsplash/eberhard-grossgasteiger-1207565-unsplash.jpg') }}');">
        <div class="hero-inner text-center">
          <h2>Congratulations</h2>
          <p class="lead">You have successfully registered with our system. Next, you can log in to the dashboard with your account.</p>
          <div class="mt-4">
            <a href="#" class="btn btn-outline-white btn-lg btn-icon icon-left"><i class="fas fa-sign-in-alt"></i> Login</a>
          </div>
        </div>
      </div>
    </div>
</div>

<h2 class="section-title">Recorder</h2>
<div class="row">
  <calibri-recorder uploadUrl="{{ route('capture.store') }}"></calibri-recorder>
</div>
@endsection

resources/views/dashboard.blade.php
@extends('layouts.backend')

@section('title', 'Analytics')

@section('content')
<div class="section-header">
	<h1>Analytics</h1>
</div>
<div class="row">
	<div class="col-sm-9">&nbsp;</div>
	<div class="col-sm-3">
		<input data-type="daterange" class="form-control pull-right"></input>
	</div>
	@include('partials.analytics.voice-mechanics')
	@include('partials.analytics.vibe')
	@include('partials.analytics.dynamics')
	@include('partials.analytics.content')
</div>
@endsection

@section('css')
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
@endsection

@section('plugin')
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
@endsection

@section('head-js')
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha256-t9UJPrESBeG2ojKTIcFLPGF7nHi2vEc7f5A2KpH/UBU=" crossorigin="anonymous"></script>
<script src="https://cdn.anychart.com/releases/v8/js/anychart-base.min.js"></script>
<script src="https://cdn.anychart.com/releases/v8/js/anychart-tag-cloud.min.js"></script>
@endsection

@section('js')
<script src="{{ asset('stisla/modules/chart.min.js') }}"></script>
<script src="{{ asset('js/pages/analytics.js') }}"></script>
@endsection

resources/views/io.blade.php
@extends('layouts.app')

@section('title', 'IO')

@section('content')
<div class="container mt-5">
    <div class="row">
        <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
            <div class="login-brand">
                <img src="https://ui-avatars.com/api/?name={{ config('app.name') }}&background=fff&color=6777ef&size=100"
                    alt="logo" width="100" class="shadow-light rounded-circle">
            </div>

            @if (session('status'))
            <div class="alert alert-info alert-dismissible show fade">
                <div class="alert-body">
                    <button class="close" data-dismiss="alert">
                        <span>×</span>
                    </button>
                    {{ session('status') }}
                </div>
            </div>
            @endif

            <div class="card card-primary">
                <div class="card-header">
                    <h4>Input & Output</h4>
                </div>

                <div class="card-body">
                    <p class="lead">Nothing to see here..</p>
                </div>
            </div>
            <div class="mt-3 text-muted text-center">
                Want to go to the homepage? <a href="{{ route('welcome') }}">Click here!</a>
            </div>
            <div class="simple-footer">
                Copyright © Calibri 2021
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/learn.blade.php
@extends('layouts.backend')

@section('title', 'Behaviors')

@section('content')
<x-section-header heading="Behaviors" breadcrumb="learn" />
<div class="row">
  <div class="col-12 mb-4">
      <div class="hero text-white hero-bg-image" style="background-image: url('{{ asset('stisla/img/unsplash/eberhard-grossgasteiger-1207565-unsplash.jpg') }}');">
        <div class="hero-inner text-center">
          <h2>Subscribe to behaviors</h2>
          <p class="lead">You have successfully registered with our system. Next, you can subscribe to behaviors with your account.</p>
          <div class="mt-4">
            <a href="#" class="btn btn-outline-white btn-lg btn-icon icon-left">
              <i class="fas fa-plus"></i> Subscribe to behaviors</a>
          </div>
        </div>
      </div>
    </div>
</div>

@foreach($topics as $i => $topic)
  @include('partials.learn.topic', ['topic' => $topic])
@endforeach
@endsection

resources/views/profile.blade.php
@extends('layouts.backend')

@section('title', 'Profile')

@section('content')
<x-section-header heading="Profile" breadcrumb="profile" />
<x-section-sub-header title="Hi! {{ Str::words(auth()->user()->name, 1, '') }}"
  lead="Change information about yourself on this page." />

<div class="row mt-sm-4">
  <div class="col-12 col-md-12 col-lg-5">
    @if (Laravel\Fortify\Features::enabled(Laravel\Fortify\Features::updateProfileInformation()))
    @include('profile.update-profile-information-form')
    @endif
    @if (false)
    <div class="card profile-widget">
      <div class="profile-widget-header">
        <img alt="image" src="{{ auth()->user()->avatar_url }}" class="rounded-circle profile-widget-picture">
        <div class="profile-widget-items">
          <div class="profile-widget-item">
            <div class="profile-widget-item-label">Posts</div>
            <div class="profile-widget-item-value">187</div>
          </div>
          <div class="profile-widget-item">
            <div class="profile-widget-item-label">Followers</div>
            <div class="profile-widget-item-value">6,8K</div>
          </div>
          <div class="profile-widget-item">
            <div class="profile-widget-item-label">Following</div>
            <div class="profile-widget-item-value">2,1K</div>
          </div>
        </div>
      </div>
      <div class="profile-widget-description">
        <div class="profile-widget-name">Ujang Maman <div class="text-muted d-inline font-weight-normal">
            <div class="slash"></div> Web Developer
          </div>
        </div>
        Ujang maman is a superhero name in <b>Indonesia</b>, especially in my family. He is not a fictional character
        but an original hero in my family, a hero for his children and for his wife. So, I use the name as a user in
        this template. Not a tribute, I'm just bored with <b>'John Doe'</b>.
      </div>
      <div class="card-footer text-center">
        <div class="font-weight-bold mb-2">Follow Ujang On</div>
        <a href="#" class="btn btn-social-icon btn-facebook mr-1">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="#" class="btn btn-social-icon btn-twitter mr-1">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="#" class="btn btn-social-icon btn-github mr-1">
          <i class="fab fa-github"></i>
        </a>
        <a href="#" class="btn btn-social-icon btn-instagram">
          <i class="fab fa-instagram"></i>
        </a>
      </div>
    </div>
    @endif
  </div>
  <div class="col-12 col-md-12 col-lg-7">
    @if (session('status'))
    <div class="alert alert-primary alert-dismissible show fade">
      <div class="alert-body">
        <button class="close" data-dismiss="alert">
          <span>&times;</span>
        </button>
        @if (session('status')=='profile-information-updated')
        Profile has been updated.
        @endif
        @if (session('status')=='password-updated')
        Password has been updated.
        @endif
        @if (session('status')=='two-factor-authentication-disabled')
        Two factor authentication disabled.
        @endif
        @if (session('status')=='two-factor-authentication-enabled')
        Two factor authentication enabled.
        @endif
        @if (session('status')=='recovery-codes-generated')
        Recovery codes generated.
        @endif
      </div>
    </div>
    @endif

    @if (Laravel\Fortify\Features::enabled(Laravel\Fortify\Features::updatePasswords()))
    @include('profile.update-password-form')
    @endif

    @if (Laravel\Fortify\Features::enabled(Laravel\Fortify\Features::twoFactorAuthentication()))
    @include('profile.two-factor-authentication-form')
    @endif
  </div>
</div>
@endsection